### ISSUE TITLE
Slight improvements to knockout-datatable.less 

### ISSUE THREAD

**Issue by ohadschn** [immense/knockout-datatable#6]
There is a slight inconsistency in the project - [ `demo.html`](https://github.com/immense/knockout-datatable/blob/master/demo.html) uses bootstrap's `glyphicon-sort-by-attributes/alt`, whereas [`knockout-datatable.less`](https://github.com/immense/knockout-datatable/blob/master/knockout-datatable.less) seems to be using Font Awesome's `icon-sort-down/up`. I think it makes more sense to stick with bootstrap, since the [demo page](http://rawgit.com/immense/knockout-datatable/master/demo.html) is already using it for pagination.

Also, I suggest using the [StackOverflow concensus no-select class](http://stackoverflow.com/questions/826782/css-rule-to-disable-text-selection-highlighting) in [knockout-datatable.less](https://github.com/immense/knockout-datatable/blob/master/knockout-datatable.less):

``` css
.noselect {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

One caveat - it is my understanding that `khtml` is not relevant anymore, so maybe get rid of it.
